---
abstract: 'Holy Quran book searchable database multi-lingual in utf-8 unicode format'
author:
  - 'Ahmed Amin Elsheshtawy <support@islamware.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.132830'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Religion-Islam-Quran
no_index:
  directory:
    - t
    - inc
requires: {}
version: 2.0
